/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadora;

/**
 *
 * @author Usuario
 */
public class CALCULADORA_ extends javax.swing.JFrame {

    private String CadenaNumeros = "";
    private String Operacion = "nula";
    private double PrimerNumeros, Resultado;
    private boolean Activado = true;
    private boolean Punto = true;

    public CALCULADORA_() {
        initComponents();
        this.setTitle("Calculadora");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        BotonC = new javax.swing.JButton();
        BotonRaiz = new javax.swing.JButton();
        BotonDivision = new javax.swing.JButton();
        BotonCE = new javax.swing.JButton();
        Boton7 = new javax.swing.JButton();
        Boton8 = new javax.swing.JButton();
        Boton9 = new javax.swing.JButton();
        BotonMultiplicar = new javax.swing.JButton();
        Boton4 = new javax.swing.JButton();
        Boton5 = new javax.swing.JButton();
        Boton6 = new javax.swing.JButton();
        BotonMenos = new javax.swing.JButton();
        BotonUno = new javax.swing.JButton();
        BotonDos = new javax.swing.JButton();
        BotonTres = new javax.swing.JButton();
        BotonSumar = new javax.swing.JButton();
        BotonCambiarSigno = new javax.swing.JButton();
        BotonCero = new javax.swing.JButton();
        BotonPunto = new javax.swing.JButton();
        BotonIgual = new javax.swing.JButton();
        Etiqueta = new javax.swing.JLabel();
        EtiquetaMuestra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 0));

        Panel.setLayout(new java.awt.GridLayout(5, 4));

        BotonC.setBackground(new java.awt.Color(204, 0, 0));
        BotonC.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BotonC.setForeground(new java.awt.Color(0, 0, 0));
        BotonC.setText("C");
        BotonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCActionPerformed(evt);
            }
        });
        Panel.add(BotonC);

        BotonRaiz.setBackground(new java.awt.Color(204, 204, 204));
        BotonRaiz.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BotonRaiz.setForeground(new java.awt.Color(0, 0, 0));
        BotonRaiz.setText("√");
        BotonRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRaizActionPerformed(evt);
            }
        });
        Panel.add(BotonRaiz);

        BotonDivision.setBackground(new java.awt.Color(204, 204, 204));
        BotonDivision.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BotonDivision.setForeground(new java.awt.Color(0, 0, 0));
        BotonDivision.setText("/");
        BotonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDivisionActionPerformed(evt);
            }
        });
        Panel.add(BotonDivision);

        BotonCE.setBackground(new java.awt.Color(204, 0, 0));
        BotonCE.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BotonCE.setForeground(new java.awt.Color(0, 0, 0));
        BotonCE.setText("CE");
        BotonCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCEActionPerformed(evt);
            }
        });
        Panel.add(BotonCE);

        Boton7.setBackground(new java.awt.Color(204, 204, 204));
        Boton7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Boton7.setForeground(new java.awt.Color(0, 0, 0));
        Boton7.setText("7");
        Boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton7ActionPerformed(evt);
            }
        });
        Panel.add(Boton7);

        Boton8.setBackground(new java.awt.Color(204, 204, 204));
        Boton8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Boton8.setForeground(new java.awt.Color(0, 0, 0));
        Boton8.setText("8");
        Boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton8ActionPerformed(evt);
            }
        });
        Panel.add(Boton8);

        Boton9.setBackground(new java.awt.Color(204, 204, 204));
        Boton9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Boton9.setForeground(new java.awt.Color(0, 0, 0));
        Boton9.setText("9");
        Boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton9ActionPerformed(evt);
            }
        });
        Panel.add(Boton9);

        BotonMultiplicar.setBackground(new java.awt.Color(204, 204, 204));
        BotonMultiplicar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BotonMultiplicar.setForeground(new java.awt.Color(0, 0, 0));
        BotonMultiplicar.setText("X");
        BotonMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMultiplicarActionPerformed(evt);
            }
        });
        Panel.add(BotonMultiplicar);

        Boton4.setBackground(new java.awt.Color(204, 204, 204));
        Boton4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Boton4.setForeground(new java.awt.Color(0, 0, 0));
        Boton4.setText("4");
        Boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton4ActionPerformed(evt);
            }
        });
        Panel.add(Boton4);

        Boton5.setBackground(new java.awt.Color(204, 204, 204));
        Boton5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Boton5.setForeground(new java.awt.Color(0, 0, 0));
        Boton5.setText("5");
        Boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton5ActionPerformed(evt);
            }
        });
        Panel.add(Boton5);

        Boton6.setBackground(new java.awt.Color(204, 204, 204));
        Boton6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Boton6.setForeground(new java.awt.Color(0, 0, 0));
        Boton6.setText("6");
        Boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton6ActionPerformed(evt);
            }
        });
        Panel.add(Boton6);

        BotonMenos.setBackground(new java.awt.Color(204, 204, 204));
        BotonMenos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BotonMenos.setForeground(new java.awt.Color(0, 0, 0));
        BotonMenos.setText("-");
        BotonMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenosActionPerformed(evt);
            }
        });
        Panel.add(BotonMenos);

        BotonUno.setBackground(new java.awt.Color(204, 204, 204));
        BotonUno.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BotonUno.setForeground(new java.awt.Color(0, 0, 0));
        BotonUno.setText("1");
        BotonUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonUnoActionPerformed(evt);
            }
        });
        Panel.add(BotonUno);

        BotonDos.setBackground(new java.awt.Color(204, 204, 204));
        BotonDos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BotonDos.setForeground(new java.awt.Color(0, 0, 0));
        BotonDos.setText("2");
        BotonDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDosActionPerformed(evt);
            }
        });
        Panel.add(BotonDos);

        BotonTres.setBackground(new java.awt.Color(204, 204, 204));
        BotonTres.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BotonTres.setForeground(new java.awt.Color(0, 0, 0));
        BotonTres.setText("3");
        BotonTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTresActionPerformed(evt);
            }
        });
        Panel.add(BotonTres);

        BotonSumar.setBackground(new java.awt.Color(204, 204, 204));
        BotonSumar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BotonSumar.setForeground(new java.awt.Color(0, 0, 0));
        BotonSumar.setText("+");
        BotonSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSumarActionPerformed(evt);
            }
        });
        Panel.add(BotonSumar);

        BotonCambiarSigno.setBackground(new java.awt.Color(204, 204, 204));
        BotonCambiarSigno.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BotonCambiarSigno.setForeground(new java.awt.Color(0, 0, 0));
        BotonCambiarSigno.setText("+/-");
        BotonCambiarSigno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCambiarSignoActionPerformed(evt);
            }
        });
        Panel.add(BotonCambiarSigno);

        BotonCero.setBackground(new java.awt.Color(204, 204, 204));
        BotonCero.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BotonCero.setForeground(new java.awt.Color(0, 0, 0));
        BotonCero.setText("0");
        BotonCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCeroActionPerformed(evt);
            }
        });
        Panel.add(BotonCero);

        BotonPunto.setBackground(new java.awt.Color(204, 204, 204));
        BotonPunto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BotonPunto.setForeground(new java.awt.Color(0, 0, 0));
        BotonPunto.setText(".");
        BotonPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPuntoActionPerformed(evt);
            }
        });
        Panel.add(BotonPunto);

        BotonIgual.setBackground(new java.awt.Color(0, 102, 0));
        BotonIgual.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BotonIgual.setForeground(new java.awt.Color(0, 0, 0));
        BotonIgual.setText("=");
        BotonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIgualActionPerformed(evt);
            }
        });
        Panel.add(BotonIgual);

        Etiqueta.setBackground(new java.awt.Color(0, 0, 0));
        Etiqueta.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        Etiqueta.setForeground(new java.awt.Color(0, 0, 0));
        Etiqueta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Etiqueta.setText("0");

        EtiquetaMuestra.setBackground(new java.awt.Color(0, 0, 0));
        EtiquetaMuestra.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        EtiquetaMuestra.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Etiqueta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EtiquetaMuestra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EtiquetaMuestra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton7ActionPerformed
        if(Etiqueta.getText().equals("0")){
            CadenaNumeros = "7";
        }else{ 
            CadenaNumeros += "7";
        }
        Etiqueta.setText(CadenaNumeros);
        Activado = true; //Voy a usar la calculadora
    }//GEN-LAST:event_Boton7ActionPerformed

    private void Boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton8ActionPerformed
        if(Etiqueta.getText().equals("0")){
            CadenaNumeros = "8";
        }else{ 
            CadenaNumeros += "8";
        }
        Etiqueta.setText(CadenaNumeros);
        Activado = true; //Voy a usar la calculadora
    }//GEN-LAST:event_Boton8ActionPerformed

    private void Boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton9ActionPerformed
        if(Etiqueta.getText().equals("0")){
            CadenaNumeros = "9";
        }else{ 
            CadenaNumeros += "9";
        }
        Etiqueta.setText(CadenaNumeros);
        Activado = true; //Voy a usar la calculadora
    }//GEN-LAST:event_Boton9ActionPerformed

    private void Boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton4ActionPerformed
        if(Etiqueta.getText().equals("0")){
            CadenaNumeros = "4";
        }else{ 
            CadenaNumeros += "4";
        }
        Etiqueta.setText(CadenaNumeros);
        Activado = true; //Voy a usar la calculadora
    }//GEN-LAST:event_Boton4ActionPerformed

    private void Boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton5ActionPerformed
        if(Etiqueta.getText().equals("0")){
            CadenaNumeros = "5";
        }else{ 
            CadenaNumeros += "5";
        }
        Etiqueta.setText(CadenaNumeros);
        Activado = true; //Voy a usar la calculadora
    }//GEN-LAST:event_Boton5ActionPerformed

    private void Boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton6ActionPerformed
        if(Etiqueta.getText().equals("0")){
            CadenaNumeros = "6";
        }else{ 
            CadenaNumeros += "6";
        }
        Etiqueta.setText(CadenaNumeros);
        Activado = true; //Voy a usar la calculadora
    }//GEN-LAST:event_Boton6ActionPerformed

    private void BotonUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonUnoActionPerformed
        if(Etiqueta.getText().equals("0")){
            CadenaNumeros = "1";
        }else{ 
            CadenaNumeros += "1";
        }
        Etiqueta.setText(CadenaNumeros);
        Activado = true; //Voy a usar la calculadora
    }//GEN-LAST:event_BotonUnoActionPerformed

    private void BotonDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDosActionPerformed
        if(Etiqueta.getText().equals("0")){
            CadenaNumeros = "2";
        }else{ 
            CadenaNumeros += "2";
        }
        Etiqueta.setText(CadenaNumeros);
        Activado = true; //Voy a usar la calculadora
    }//GEN-LAST:event_BotonDosActionPerformed

    private void BotonTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTresActionPerformed
        if(Etiqueta.getText().equals("0")){
            CadenaNumeros = "3";
        }else{ 
            CadenaNumeros += "3";
        }
        Etiqueta.setText(CadenaNumeros);
        Activado = true; //Voy a usar la calculadora
    }//GEN-LAST:event_BotonTresActionPerformed

    private void BotonCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCeroActionPerformed
        if(Etiqueta.getText().equals("0")){
            CadenaNumeros = "0";
        }else{ 
            CadenaNumeros += "0";
        }
        Etiqueta.setText(CadenaNumeros);
        Activado = true; //Voy a usar la calculadora
    }//GEN-LAST:event_BotonCeroActionPerformed

    private void BotonSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSumarActionPerformed
        if(Activado == true){
            PrimerNumeros = Double.parseDouble(CadenaNumeros);
            EtiquetaMuestra.setText( CadenaNumeros + " + ");
            CadenaNumeros = "";
            Operacion = "sumar";
            
            Activado = false;
        }
    }//GEN-LAST:event_BotonSumarActionPerformed

    private void BotonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIgualActionPerformed
        double SegundoNumeros;
        if(Operacion.equals("nula")){
            Etiqueta.setText(CadenaNumeros);
        }
        else if(Operacion.equals("sumar")){
            SegundoNumeros = Double.parseDouble(CadenaNumeros);
            Resultado = PrimerNumeros + SegundoNumeros;
            Etiqueta.setText(String.format("% .2f",Resultado));
            CadenaNumeros = String.valueOf(Resultado);
            Operacion = "nula";
        }
        else if(Operacion.equals("restar")){
            SegundoNumeros = Double.parseDouble(CadenaNumeros);
            Resultado = PrimerNumeros - SegundoNumeros;
            Etiqueta.setText(String.format("% .2f",Resultado));
            CadenaNumeros = String.valueOf(Resultado);
            Operacion = "nula";
        }
        else if(Operacion.equals("multiplicar")){
            SegundoNumeros = Double.parseDouble(CadenaNumeros);
            Resultado = PrimerNumeros * SegundoNumeros;
            Etiqueta.setText(String.format("% .2f",Resultado));
            CadenaNumeros = String.valueOf(Resultado);
            Operacion = "nula";
        }
        else if(Operacion.equals("dividir")){
            SegundoNumeros = Double.parseDouble(CadenaNumeros);
            if(SegundoNumeros == 0){
                Etiqueta.setText("NoSeDivideX0");
            }else{
                Resultado = PrimerNumeros / SegundoNumeros;
                Etiqueta.setText(String.format("% .2f",Resultado));
                CadenaNumeros = String.valueOf(Resultado);
                Operacion = "nula";
            }
        }
        EtiquetaMuestra.setText("");
        Activado = true;
    }//GEN-LAST:event_BotonIgualActionPerformed

    private void BotonMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenosActionPerformed
        if(Activado == true){
            PrimerNumeros = Double.parseDouble(CadenaNumeros);
            EtiquetaMuestra.setText( CadenaNumeros + " - ");
            CadenaNumeros = "";
            Operacion = "restar";
            
            Activado = false;
        }
    }//GEN-LAST:event_BotonMenosActionPerformed

    private void BotonMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMultiplicarActionPerformed
        if(Activado == true){
            PrimerNumeros = Double.parseDouble(CadenaNumeros);
            EtiquetaMuestra.setText( CadenaNumeros + " * ");
            CadenaNumeros = "";
            Operacion = "multiplicar";
            
            Activado = false;
            Punto = true;
        }
    }//GEN-LAST:event_BotonMultiplicarActionPerformed

    private void BotonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDivisionActionPerformed
        if(Activado == true){
            PrimerNumeros = Double.parseDouble(CadenaNumeros);
            EtiquetaMuestra.setText( CadenaNumeros + " / ");
            CadenaNumeros = "";
            Operacion = "dividir";
            
            Activado = false;
        }
    }//GEN-LAST:event_BotonDivisionActionPerformed

    private void BotonRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRaizActionPerformed
        PrimerNumeros = Double.parseDouble(CadenaNumeros);
        EtiquetaMuestra.setText("sqrt("+CadenaNumeros+")");
        Resultado = Math.sqrt(PrimerNumeros);
        Etiqueta.setText(String.format("%.2f", Resultado));
        CadenaNumeros = String.valueOf(Resultado); // Convertimos el valor a cadena
        Punto = true;
    }//GEN-LAST:event_BotonRaizActionPerformed

    private void BotonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPuntoActionPerformed
        if(Punto == true){
            if(CadenaNumeros.equals("")){
                CadenaNumeros = "0.";
            }else{
                CadenaNumeros += ".";
            }
            Etiqueta.setText(CadenaNumeros);
            Punto = false;
        }
    }//GEN-LAST:event_BotonPuntoActionPerformed

    private void BotonCambiarSignoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCambiarSignoActionPerformed
        if(CadenaNumeros.charAt(0) != '-' ) {
            CadenaNumeros = "-" + CadenaNumeros;  
        }else{
            CadenaNumeros = CadenaNumeros.substring(1, CadenaNumeros.length());  
        }
        Etiqueta.setText(CadenaNumeros);
    }//GEN-LAST:event_BotonCambiarSignoActionPerformed

    private void BotonCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCEActionPerformed
        int Tamaño = CadenaNumeros.length();
        if(Tamaño > 0){
            if(Tamaño == 1){
                CadenaNumeros = "0";
            }else{
                CadenaNumeros = CadenaNumeros.substring(0,CadenaNumeros.length()- 1);
            }
            Etiqueta.setText(CadenaNumeros);
        }
    }//GEN-LAST:event_BotonCEActionPerformed

    private void BotonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCActionPerformed
        EtiquetaMuestra.setText("");
        Etiqueta.setText("0");
        Operacion = "nula";
        CadenaNumeros = "";
        Activado = true;
        Punto = true;
    }//GEN-LAST:event_BotonCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CALCULADORA_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CALCULADORA_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CALCULADORA_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CALCULADORA_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CALCULADORA_().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton4;
    private javax.swing.JButton Boton5;
    private javax.swing.JButton Boton6;
    private javax.swing.JButton Boton7;
    private javax.swing.JButton Boton8;
    private javax.swing.JButton Boton9;
    private javax.swing.JButton BotonC;
    private javax.swing.JButton BotonCE;
    private javax.swing.JButton BotonCambiarSigno;
    private javax.swing.JButton BotonCero;
    private javax.swing.JButton BotonDivision;
    private javax.swing.JButton BotonDos;
    private javax.swing.JButton BotonIgual;
    private javax.swing.JButton BotonMenos;
    private javax.swing.JButton BotonMultiplicar;
    private javax.swing.JButton BotonPunto;
    private javax.swing.JButton BotonRaiz;
    private javax.swing.JButton BotonSumar;
    private javax.swing.JButton BotonTres;
    private javax.swing.JButton BotonUno;
    private javax.swing.JLabel Etiqueta;
    private javax.swing.JLabel EtiquetaMuestra;
    private javax.swing.JPanel Panel;
    // End of variables declaration//GEN-END:variables
}
